### ISSUE TITLE
querySummaryForDevice() restricted to pre-embedded applications

### ISSUE THREAD

**Issue by cuihtlauac** [msalah104/NSTDemo#6]
Currently, both master and fix-nougat branches use `querySummaryForDevice()`. According to the [NetworkStatsManager](`https://developer.android.com/reference/android/app/usage/NetworkStatsManager.html`) documentation class, the method requires the `PACKAGE_USAGE_STATS` permission, which is system level, therefore restricted to pre-embedded applications. Android studio displays a warning about that in the manifest.

Right now, it crashes: 

    02-01 08:58:00.765 3927-3927/com.orang.nstdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.orang.nstdemo, PID: 3927
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {com.orang.nstdemo/com.orang.nstdemo.Activity}: java.lang.SecurityException: Calling package com.orang.nstdemo cannot access device summary network stats
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4089)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
    Caused by: java.lang.SecurityException: Calling package com.orang.nstdemo cannot access device summary network stats
       at android.os.Parcel.readException(Parcel.java:1684)
       at android.os.Parcel.readException(Parcel.java:1637)
       at android.net.INetworkStatsSession$Stub$Proxy.getDeviceSummaryForNetwork(INetworkStatsSession.java:259)
       at android.app.usage.NetworkStats.getDeviceSummaryForNetwork(NetworkStats.java:401)
       at android.app.usage.NetworkStatsManager.querySummaryForDevice(NetworkStatsManager.java:135)
       at com.orang.nstdemo.Helper.queryForDataUsage(Helper.java:73)
       at com.orang.nstdemo.Helper.addNewQuery(Helper.java:54)
       at com.orang.nstdemo.Activity.onActivityResult(Activity.java:71)
       at android.app.Activity.dispatchActivityResult(Activity.java:6932)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) 
       at android.app.ActivityThread.-wrap20(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:154) 
       at android.app.ActivityThread.main(ActivityThread.java:6119) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by msalah104** [comment]
Do you give the app permission from the settings (manually) Settings -> Security  -> App With Usage Access And giving the app the required permission.
